---
- name: Verify
  hosts: localhost
  gather_facts: false
  roles:
    - fake_modules
  tasks:
    - shell: pwd
    - shell: ls
    - command: whoami
    - assert:
        that: "{{item}}"
      with_random_choice:
          - false
          - true
...

